spring:
  datasource:
    url: jdbc:mysql://1.15.13.149:3306/novel?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456